version: '3.9'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    restart: always
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
      - 'SERVER_BASEPATH=/opensearch-dashboard'
      - 'SERVER_REWRITEBASEPATH=true'
