stages:
  - fluent-bit

variables:
   ANALYSIS_HOST: 192.168.200.34

.job_inj:
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_ROOT_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - ssh-keyscan -t ed25519 ${ANALYSIS_HOST} >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh
    - export DOCKER_HOST="ssh://${CI_SSH_USERNAME}@${ANALYSIS_HOST}"

deploy_mariadb:
  stage: fluent-bit
  tags:
    - Docker
  when: manual
  only:
    refs:
      - main
  extends: .job_inj
  script:
    - docker compose up -d
