---
stages:
  - keepalived
  - delete_keepalived

.job_inj:
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_ROOT_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - ssh-keyscan -t ed25519 ${ADD0_PUB} ${ADD1_PUB} >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh

deploy_keepalived:
  stage: keepalived
  tags:
    - Docker
  when: manual
  only:
    refs:
      - main
  extends: .job_inj
  script:
    - export DOCKER_HOST="ssh://${CI_SSH_USERNAME}@${ADD0_PUB}"
    - docker compose -f vip0-compose.yml up -d
    - export DOCKER_HOST="ssh://${CI_SSH_USERNAME}@${ADD1_PUB}"
    - docker compose -f vip1-compose.yml up -d

destroy_keepalived:
  stage: delete_keepalived
  tags:
    - Docker
  when: manual
  only:
    refs:
      - main
  extends: .job_inj
  script:
    - export DOCKER_HOST="ssh://${CI_SSH_USERNAME}@${ADD0_PUB}"
    - docker compose -f vip0-compose.yml down
    - export DOCKER_HOST="ssh://${CI_SSH_USERNAME}@${ADD1_PUB}"
    - docker compose -f vip1-compose.yml down
