---
version: '3.9'

services:
  master:
    image: rootshellcoder/swarm-keepalived:latest
    environment:
      KEEPALIVED_UNICAST_SRC_IP: "APP0_PUB"
      KEEPALIVED_UNICAST_PEER: "APP0_PUB, APP1_PUB"
      KEEPALIVED_VIRTUAL_IPADDRESS: "192.168.200.34"
      KEEPALIVED_PRIORITY: "200"
      KEEPALIVED_INTERFACE: "enp1s0"
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
