---

stages:
  - ansible_test
  - lint_test
  - prepare_system

image: leshevi1/lin-ansible

variables:
  ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  ANSIBLE_ROLES_PATH: roles
  ANSIBLE_INVENTORY: inventories
  ANSIBLE_REMOTE_TMP: /tmp
  ANSIBLE_FORCE_COLOR: 'true'
  ANSIBLE_STARATEGY: linear
  ANSIBLE_PIPELINING: 1
  ANSIBLE_TRANSPORT: ssh
  ANSIBLE_BECOME_EXE: sudo
  ANSIBLE_BECOME_USER: root
  ANSIBLE_BECOME_ASKPASS: 'False'
  ANSIBLE_FORCE_HANDLER: 'True'
  ANSIBLE_STDOUT_CALLBACK: yaml
  ANSIBLE_ASK_PASS: 'False'
  ANSIBLE_NOCOWS: 1
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  DEPRECATION_WARNINGS: 'false'

.job_inj:
  before_script:
    - rm .gitlab-ci.yml README.md
    - eval $(ssh-agent -s)
    - echo "$SSH_ROOT_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - |+
      sed -i "s!MON_PUB!${MON_PUB}!" inventories/hosts.yml
      sed -i "s!APP0_PUB!${APP0_PUB}!" inventories/hosts.yml
      sed -i "s!APP1_PUB!${APP1_PUB}!" inventories/hosts.yml
      sed -i "s!DB_PUB!${DB_PUB}!" inventories/hosts.yml
    - cat inventories/hosts.yml

ansible_test:
  stage: ansible_test
  when: manual
  only:
    refs:
      - main
  tags:
    - Docker
  script:
    - ansible --version
    - ansible-lint --version

ansible_lint_test:
  stage: lint_test
  when: manual
  tags:
    - Docker
  only:
    refs:
      - main
    changes:
      - "inventories/**/*"
      - "playbooks/**/*"
      - "roles/**/*"
      - ".gitlab-ci.yml"
  extends: .job_inj
  script:
    - ansible-lint -q --offline

ansible_prepare_system:
  stage: prepare_system
  tags:
    - Docker
  only:
    refs:
      - main
    changes:
      - "inventories/**/*"
      - "playbooks/**/*"
      - "roles/**/*"
      - ".gitlab-ci.yml"
  needs:
    - ansible_lint_test
  extends: .job_inj
  script:
    - ansible-playbook playbooks/prepare.yml
    - ansible-playbook playbooks/prepare_nfs.yml
    - ansible-playbook playbooks/wordpress_nfs.yml
    - ansible-playbook playbooks/prometheus.yml
    - ansible-playbook playbooks/grafana.yml
    - ansible-playbook playbooks/docker.yml





